### ISSUE TITLE
not able to run learn.py script 

### ISSUE THREAD

**Issue by Pratikhyadav** [Liang-yc/CalorieEstimation#1]
Hello,

I clone your project and tried to run learn.py script, but getting followinng error

$ python learn.py
Traceback (most recent call last):
  File "learn.py", line 3, in <module>
    from create_feature import *
  File "/home/pratik/Desktop/Python/Calorie-estimation-from-food-images-OpenCV-master/create_feature.py", line 4, in <module>
    from img_seg import *
  File "/home/pratik/Desktop/Python/Calorie-estimation-from-food-images-OpenCV-master/img_seg.py", line 7
    img_filt = cv2.medianBlur( img, 5)
           ^
SyntaxError: invalid syntax

Also have some question regarding how to use this project

1) From where it will fetch image?
2) Can you provide proper step to run it correctly with example

Let me know if your need more detail

**Comment by Liang-yc** [comment]
`medianBlur`  function maybe different if you use new `opencv-python` package. Please check `opencv` documentation. And you do not need to fetch images. If you want to run this porject, you should read [readme](https://github.com/Liang-yc/CalorieEstimation/tree/master/faster_rcnn-master) and run `script_faster_rcnn_VOC2007_ZF.m` for training stage. All the image dataset can be downloaded from my another [repo](https://github.com/Liang-yc/ECUSTFD-resized-).
